#!/usr/bin/env python3
"""Build src/data/catalog.js from a Proxibid scrape plus per-product analysis.

Usage: python3 scripts/build-catalog.py <lots.txt> <products.json> <analysis*.json>... <img-status.txt>

lots.txt      LOT|TITLE|CURRENT_BID|LOT_INFORMATION_ID  (one line per lot, catalog order)
products.json [{key, title}, ...]  (unique titles → product key)
analysis*.json {key: {v, cat, name, sub, mkt, notes, verdict, roi}}
img-status.txt "<lot> <http status>" for the FullDetail image of each lot
"""
import json, sys

lots_path, products_path, *rest = sys.argv[1:]
img_path = rest.pop()
analysis = {}
for p in rest:
    analysis.update(json.load(open(p)))

products = json.load(open(products_path))
key_by_title = {p["title"]: p["key"] for p in products}
has_img = {l.split()[0]: l.split()[1] == "200" for l in open(img_path) if l.strip()}

missing = [p["key"] for p in products if p["key"] not in analysis]
if missing:
    sys.exit(f"missing analysis for: {missing}")

out_products = {}
for p in products:
    a = analysis[p["key"]]
    out_products[p["key"]] = {"title": p["title"], **{k: a[k] for k in ("v", "cat", "name", "sub", "mkt", "notes", "verdict", "roi")}}

rows = []
for line in open(lots_path):
    lot, title, bid, lot_id = line.rstrip("\n").split("|")
    rows.append([lot, int(lot_id), float(bid), key_by_title[title], 1 if has_img.get(lot) else 0])

auction = {
    "id": 299465,
    "sellerId": 11431,
    "seller": "SD Surplus Auctions",
    "title": "Oct 8th Biotech, Laboratory, Electronics & Industrial",
    "dateLabel": "October 8",
    "pages": 21,
    "url": "https://www.proxibid.com/SD-Surplus-Auctions/Oct8th-Biotech-Laboratory-Electronics-Industrial/event-catalog/299465",
    "snapshotLabel": "Oct 8, 2026",
}

with open("src/data/catalog.js", "w") as f:
    f.write("// GENERATED by scripts/build-catalog.py — do not edit by hand.\n")
    f.write(f"// {len(rows)} lots / {len(out_products)} unique products from Proxibid auction {auction['id']}.\n\n")
    f.write("export const AUCTION = " + json.dumps(auction, indent=2, ensure_ascii=False) + ";\n\n")
    f.write("export const PRODUCTS = {\n")
    for k, v in out_products.items():
        f.write(f"  {k}: {json.dumps(v, ensure_ascii=False)},\n")
    f.write("};\n\n")
    f.write("// [lot, lotInformationId, currentHighBid, productKey, hasImage]\n")
    f.write("export const LOTS = [\n")
    for r in rows:
        f.write("  " + json.dumps(r, ensure_ascii=False) + ",\n")
    f.write("];\n")
print(f"wrote {len(rows)} lots, {len(out_products)} products")
